name: Deploy Website to DirectAdmin

on:
  repository_dispatch:
    types: [wp_trigger_build]

  push:
    branches:
      - master

jobs:
  web-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      # Lấy source code
      - name: Checkout source
        uses: actions/checkout@v4

      # Cài Node.js + cache pnpm
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "pnpm"

      # Cài pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      # Cài dependencies
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # Tạo file .env từ GitHub Secrets
      - name: Make .env
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      # Build project
      - name: Build Project
        run: pnpm run build-git

      # Chuẩn bị file deploy
      - name: Zip Build Folder
        run: |
          mkdir deploy

          cp .env deploy/
          cp -r dist/* deploy/

          cd deploy
          zip -r ../escvn.zip .

      # Upload file zip lên hosting
      - name: Sync files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /public_html/
          dangerous-clean-slate: false
          include: |
            escvn.zip
          exclude: |
            **
            !escvn.zip

      # Gọi script giải nén trên hosting
      - name: Trigger Remote Unzip
        run: |
          source .env
          curl -s "$WC_URL/unzip.php"